forward IDs given by DataList::relation()
silverstripe/silverstripe-blog pull request #621
Opened 2020-08-25 14:47 UTC by wernerkrauss

This way calling `->relation('BlogPosts')` does not return an UnsavedRelationList

fixes #619

2020-08-26 18:36 UTC, dnsl48 commented
Thank you for the PR!

## merge checklist
 
* [ ] the target branch is [correct](https://docs.silverstripe.org/en/4/contributing/code/#picking-the-right-version)
* [ ] all commits are relevant (e.g. no debugging and linting)
* [ ] the commit messages follow [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)
* [ ] the patch follows [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/)
* [ ] new features are covered with tests (back-end with unit tests, front-end with Behat)
* [ ] the relevant CMS documentation is updated; changelog for impactful changes
* [ ] CI is green
* [ ] at least one peer reviewer approved; no changes requested

2020-08-26 18:54 UTC, dnsl48 requested changes
Looks good. Just need to add the new param documentation

2020-08-26 18:54 UTC, dnsl48 commented on src/Model/BlogObject.php
> +    public function BlogPosts($id = null)
Could you please add `@param int $id ...` to the method documentation?

2020-08-26 18:59 UTC, dnsl48 commented
The branch `master` is reserved for a future MAJOR release, which is supposed to be version `4` of this module. However, I think this patch should end up in the next MINOR release, which is going to be `3.6`.

@wernerkrauss to do that, could you please retarget the branch `3` of this repository instead of `master`?

2020-08-26 19:00 UTC, dnsl48 commented
@wernerkrauss to follow the commit message convention, could you add a prefix "FIX" to the commit message? So it may look like that: 
`FIX forward IDs given by DataList::relation()`

2020-08-27 14:33 UTC, wernerkrauss commented on src/Model/BlogObject.php
> +    public function BlogPosts($id = null)
I added the documentation and took the explanation from `DataObject::getComponents()`

2020-08-27 23:23 UTC, dnsl48 requested changes

2020-08-27 23:23 UTC, dnsl48 commented on src/Model/BlogObject.php
> +     * @param int|array $id Optional ID(s) for parent of this relation
```suggestion
     * @param int|array|null $id Optional ID(s) for parent of this relation
```

2020-09-07 20:15 UTC, dnsl48 approved these changes
Thank you for the contribution!

2020-09-07 20:15 UTC, merged