Fix category and tag buttons using input groups from bootstrap
silverstripe/silverstripe-blog pull request #624
Opened 2020-10-01 09:20 UTC by MarcioBarrientos

This fixes the category and tag button layout.
![Captura de Pantalla 2020-10-01 a la(s) 03 09 29](https://user-images.githubusercontent.com/4836851/94791501-f5464b80-0394-11eb-8220-11de15a2e276.png)

2020-10-01 10:28 UTC, dhensby requested changes
I think we need a more generic solution than relying on there being only 2 fields

2020-10-01 10:28 UTC, dhensby commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
This doesn't seem like a good way to do this. Shouldn't it be more generic? Like if it's the last item or if it's a form action (button)?

2020-10-01 15:24 UTC, MarcioBarrientos commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
@dhensby I tried but I cant get a form action because it iterates an ArrayList and not a Form and always will be a 2 fields. Maybe this is better?
`<div class="add-existing-autocompleter">
    <div class="input-group">
        <% loop $Fields %>
            <% if not $Last %>
                $Field
            <% else %>
                <div class="input-group-append">
                    $Field
                </div>
            <% end_if %>
        <% end_loop %>
	</div>
</div>`

2020-10-01 16:13 UTC, dhensby commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
You should be able to use `$Field.Type == 'action'`

2020-10-01 16:46 UTC, MarcioBarrientos commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
@dhensby No, I can't get the Type property, I already did a debug and the only property that returns data is "Value", it returns a text input or the button without any indicator that I can use.

2020-10-01 16:50 UTC, dhensby commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
Ah, have you tried just `$Type`?

2020-10-01 19:07 UTC, MarcioBarrientos commented on templates/SilverStripe/Blog/Forms/GridField/GridFieldAddByDBField.ss
> +            <% if $Pos == 2 %>
@dhensby Yes, that did work

2020-10-01 19:09 UTC, dhensby commented
@MarcioBarrientos can you squash your two commits, please? Then I think this is good to merge

2020-10-02 09:07 UTC, dhensby approved these changes

2020-10-02 09:07 UTC, merged