MNT Add behat tests
silverstripe/silverstripe-blog pull request #660
Opened 2021-09-13 03:52 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/473

2021-09-20 10:43 UTC, michalkleiner commented on tests/behat/src/FeatureContext.php
> +    private function getDecendantHtmlField($element, $locator)
```suggestion
    private function getDescendantHtmlField($element, $locator)
```

2021-10-01 06:44 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
> +    private function getDecendantHtmlField($element, $locator)
Updated

2021-11-15 01:12 UTC, maxime-rainville requested changes
Build is sill failing

2021-11-15 01:14 UTC, emteknetnz commented
Yeah this seems like an actual regression with comments, unrelated to the added behat tests

2021-11-15 04:10 UTC, emteknetnz commented
I simply don't understand why commenting is not working in behat and I've spend far too long trying to get this to work, so will just have to stick to manual testing for this one

2021-11-18 04:05 UTC, maxime-rainville approved these changes
LGTM

2021-11-18 04:11 UTC, merged