Allow multibyte to be configured (fixes #605)
silverstripe/silverstripe-blog pull request #685
Opened 2022-08-22 03:37 UTC by wilr

2022-09-07 04:02 UTC, emteknetnz requested changes

2022-09-07 04:02 UTC, emteknetnz commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
Where is the `allow_multibyte` config defined?  I couldn't find it?  The closest config I could find was `default_allow_multibyte` which is defined on `URLSegmentFilter`.

If this is just a random, non-API piece of config then I'm not keen on this.

Also, if we do allow turning this off via config, based on the code comment there's further UI work that also needs to be done?

2022-09-07 07:59 UTC, wilr commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
`BlogObject` is a trait which can be applied to anything Categories, Tags out of the box but anything project specific such as topic or (particular author profile sections in our case). So it doesn't make much sense for it to be defined somewhere.

As far as I can tell turning it off has no issues on our site but this change leaves the default as is so whatever issue there is can be looked at in the future.

2022-09-07 21:47 UTC, emteknetnz commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
Are there any other examples of "undefined trait config" being used anywhere? If there are then this is probably OK, though if not I'm not keen to introduce a new way of using config, given peoples existing expectations that each piece of config has a corresponding `private static` that defines it.

2022-09-07 22:26 UTC, wilr commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
`Are there any other examples of "undefined trait config" being used anywhere?`

Probably not yet because we don't use traits a huge amount at this stage in core.

2022-09-07 23:18 UTC, emteknetnz commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
What happens if you put the `private static $allow_multibyte = true` on the trait?  Is the config not added to the classes the that use the trait - meaning you'd still need the `$this->config()->get('allow_multibyte') ?? true` style check?

Perhaps it would have been better if the trait was a DataExtension so that config is automatically applied to DataObjects it is applied to.  Too late for that I suppose.

I have a pretty big objection to undefined 'dynamic' API such as https://php.watch/versions/8.2/dynamic-properties-deprecated which has caused issues on the queued-jobs module.  As a maintainer who obsesses over semver and backwards compatibility, dynamic API is pretty awful.

Would it work if the trait had something like this so that it works with the existing (admittedly clunky) way of working?

**BlogObject.php**
```php
private function getAllowMultibyte(): bool
{
    $allowMultiByte = true;
    $this->extend('updateAllowMultibyte', $allowMultiByte);
    return $allowMultiByte;
}
```
And then add a extension classes to set this to false on Categories, Tags, etc?

2022-09-08 04:33 UTC, wilr commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
Seems vastly over the top and complex for what is (hopefully) a short term work around within a patch release but if that's what works then happy to do it via extension hooks.

2022-12-19 21:45 UTC, lerni commented on src/Model/BlogObject.php
> +        $filter->setAllowMultibyte($this->config()->get('allow_multibyte') ?? true);
Movement on this would be nice. A dedicated URLSegment proved to work best for me. Not sure if it's still the case but also `RedirectorPage` used to break with global mulitibyte Links set. https://github.com/silverstripe/silverstripe-blog/issues/484#issuecomment-342806753

2023-10-08 22:55 UTC, GuySartorelli commented
I'm going to close this due to lack of action. If someone would like to pick up this work feel free to create a new PR with the requested change applied.

2023-10-08 22:59 UTC, wilr commented
Hi @GuySartorelli What diud you want to see changed? As per my last comment the requested changes I don't agree with and as @lerni pointed out - the fix does what it says on the tin

2023-10-08 23:00 UTC, wilr commented
> Perhaps it would have been better if the trait was a DataExtension so that config is automatically applied to DataObjects it is applied to. 

Perhaps it would be that would require a major API change compared to the current proposed fix which retains existing API.

2023-10-08 23:14 UTC, GuySartorelli commented
Sounded like Steve was leaning towards preferring an extension to update the value, e.g.
```php
$allowMultiByte = true;
$this->extend('updateAllowUrlSegmentMultibyte', $allowMultiByte);
$filter->setAllowMultibyte($allowMultiByte);
```

Personally I do prefer the config approach, so I'd probably be okay with your existing PR if the config name was a little more specific - `allow_multibyte` could easily be used as a config name for allow multibyte for just about any purpose entirely unrelated to this specific use case. If you changed it so something more like `allow_urlsegment_multibyte` I would be okay with it.

It _is_ preferable to declare `private static` for new config, but you can't override it on the class if you add that to the trait. Perhaps the solution that would satisfy Steve then is to add those `private static` declarations on the classes included in this module which _do_ use the trait, so it is explicitly declared where we have the control to do so.

2023-10-09 00:39 UTC, wilr commented
@GuySartorelli Done.

2023-10-09 00:53 UTC, GuySartorelli requested changes
Nice, thanks for that. Just a small change to make per below.

2023-10-09 00:53 UTC, GuySartorelli commented on src/Model/BlogCategory.php
> + *
```suggestion
```
May as well just remove that - no need to have two empty lines here.
I won't hold back merging if this isn't done though.

2023-10-09 00:53 UTC, GuySartorelli commented on src/Model/BlogCategory.php
> +    private static $allow_urlsegment_multibyte = true;
```suggestion
    private static bool $allow_urlsegment_multibyte = true;
```
- `@config` is implied and is likely to be removed in a future major release anyway.
- We prefer to explicitly type-hint new API, even config. It's not enforced currently but could be in the future, and typehinting now will reduce the effort to have full typehinting across the board in the future.

2023-10-09 00:53 UTC, GuySartorelli commented on src/Model/BlogCategory.php
> +    private static $allow_urlsegment_multibyte = true;
Please do this for `BlogTag` as well.

2023-10-09 07:47 UTC, GuySartorelli approved these changes
Looks good to me. Thanks.

2023-10-09 07:48 UTC, merged

2023-11-10 08:31 UTC, lerni commented
Now in BlogController.php `rawurlencode` is triggered based on the config value from `URLSegmentFilter` but it should respect the `SilverStripe\Blog\Model\BlogCategory: allow_urlsegment_multibyte: true`and the "global" config as fallback.
`
https://github.com/silverstripe/silverstripe-blog/blob/4/src/Model/BlogController.php#L114
https://github.com/silverstripe/silverstripe-blog/blob/4/src/Model/BlogController.php#L273
https://github.com/silverstripe/silverstripe-blog/blob/4/src/Model/BlogController.php#L323