ENH Replace ADMIN permissions with less permissions in Behat test
silverstripe/silverstripe-blog pull request #687
Opened 2022-08-31 01:19 UTC by sabina-talipova

### Description
Replace user with "Admin" permissions to user with "Editor" permissions.

### Parent issue
- https://github.com/silverstripe/silverstripe-behat-extension/issues/220

2022-09-06 00:16 UTC, GuySartorelli requested changes

2022-09-06 00:16 UTC, GuySartorelli commented on tests/behat/features/blog.feature
> +    Given the "group" "EDITOR group" has permissions "Access to 'Pages' section"
```suggestion
    Given the "group" "EDITOR" has permissions "Access to 'Pages' section"
```
The name of the group shouldn't have "group" in it

2022-09-06 00:16 UTC, GuySartorelli commented on tests/behat/features/blog.feature
> +    # And I am logged in with "ADMIN" permissions
Don't have commented out code like this. If it's not needed, just remove it. If you do remove it, remove the comment as well.

2022-09-12 04:12 UTC, sabina-talipova commented on tests/behat/features/blog.feature
> +    # And I am logged in with "ADMIN" permissions
DONE

2022-09-12 04:13 UTC, sabina-talipova commented on tests/behat/features/blog.feature
> +    Given the "group" "EDITOR group" has permissions "Access to 'Pages' section"
DONE

2022-09-12 22:22 UTC, GuySartorelli commented on tests/behat/features/blog.feature
>      # Login then logout to created member
```suggestion
```
This comment refers to the part you deleted.

2022-09-12 22:22 UTC, GuySartorelli commented on tests/behat/features/blog.feature
> -    # Logout
Why are you removing this comment?

2022-09-12 22:22 UTC, GuySartorelli commented on tests/behat/features/blog.feature
> +    And I wait for 2 seconds
Why have you added this?

2022-09-13 00:36 UTC, sabina-talipova commented on tests/behat/features/blog.feature
> +    And I wait for 2 seconds
Removed. "Click Publish button" breaks test execution and throws alert message in local environment without this delay.

2022-09-13 00:38 UTC, sabina-talipova commented on tests/behat/features/blog.feature
> -    # Logout
DONE

2022-09-13 00:38 UTC, sabina-talipova commented on tests/behat/features/blog.feature
>      # Login then logout to created member
DONE

2022-09-14 01:02 UTC, GuySartorelli approved these changes

2022-09-14 01:02 UTC, merged