DEP PHP Support in CMS5
silverstripe/silverstripe-blog pull request #693
Opened 2022-12-09 02:11 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10402

2022-12-21 03:33 UTC, sabina-talipova commented
Requires https://github.com/silverstripe/silverstripe-widgets/pull/193

2023-01-10 22:12 UTC, sabina-talipova commented
Created new card for failed Behat tests https://github.com/silverstripe/silverstripe-blog/issues/696

2023-01-12 20:48 UTC, maxime-rainville reviewed
Looks fine. Just curious about why the changes to the test were needed.

2023-01-12 20:48 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> -    protected static $use_draft_site = true;
Why did we change this?

2023-01-12 20:48 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
Why was this changed?

2023-01-12 20:54 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> -    protected static $use_draft_site = true;
`use_draft_site` has been deprecated. 

https://github.com/silverstripe/silverstripe-framework/blob/2c105cffc9436a0587381956118fe3361bad04d6/src/Dev/FunctionalTest.php#L70

2023-01-12 21:08 UTC, sabina-talipova commented on tests/php/BlogFunctionalTest.php
> -    protected static $use_draft_site = true;
$use_draft_site is deprecated. We removed it [here](https://github.com/silverstripe/silverstripe-framework/pull/10594/files#diff-542dfb607458124757d02f52f7a504dab59b280168ee8574a89e163c3f64581aL46-L53)

2023-01-12 21:09 UTC, maxime-rainville requested changes
Answered my own question.

I just think we should use the more minimal `VIEW_DRAFT_CONTENT` permission to run the test.

2023-01-12 21:09 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
```suggestion
        $this->logInWithPermission('VIEW_DRAFT_CONTENT');
```

2023-01-12 21:09 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
```suggestion
        $this->logInWithPermission('VIEW_DRAFT_CONTENT');
```

2023-01-12 21:09 UTC, maxime-rainville commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
```suggestion
        $this->logInWithPermission('VIEW_DRAFT_CONTENT');
```

2023-01-12 21:09 UTC, maxime-rainville commented on tests/php/Model/BlogControllerFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
```suggestion
        $this->logInWithPermission('VIEW_DRAFT_CONTENT');
```

2023-01-12 21:09 UTC, maxime-rainville commented on tests/php/Model/BlogControllerFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
```suggestion
        $this->logInWithPermission('VIEW_DRAFT_CONTENT');
```

2023-01-12 21:10 UTC, sabina-talipova commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
User doesn't have an access to the Draft page without Admin permission

2023-01-12 21:47 UTC, sabina-talipova commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
DONE

2023-01-12 21:47 UTC, sabina-talipova commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
DONE

2023-01-12 21:47 UTC, sabina-talipova commented on tests/php/BlogFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
DONE

2023-01-12 21:47 UTC, sabina-talipova commented on tests/php/Model/BlogControllerFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
DONE

2023-01-12 21:47 UTC, sabina-talipova commented on tests/php/Model/BlogControllerFunctionalTest.php
> +        $this->logInWithPermission('ADMIN');
DONE

2023-01-12 21:50 UTC, maxime-rainville approved these changes
LGTM

2023-01-12 21:51 UTC, merged