DEP Upgrade frontend build stack
silverstripe/silverstripe-blog pull request #697
Opened 2023-01-20 02:46 UTC by GuySartorelli

Relies on the following additional PRs to work:
- https://github.com/silverstripe/silverstripe-behat-extension/pull/236
- https://github.com/silverstripe/silverstripe-widgets/pull/194
- https://github.com/silverstripe/silverstripe-tagfield/pull/229
- https://github.com/silverstripe/silverstripe-comments/pull/358

## Parent issue 
- https://github.com/silverstripeltd/product-issues/issues/644

2023-02-01 21:38 UTC, emteknetnz requested changes
Failing behat tests after rerun after merging other PRs

2023-02-02 02:59 UTC, GuySartorelli commented
I can reproduce the failures locally. Will look at them next week.

2023-02-06 23:08 UTC, GuySartorelli commented
This failure also happens when running behat tests without this PR (if you update the feature to correctly set the categories and tags). Whatever is causing the failure, it's not caused by this PR.
The behaviour the behat test is covering _does_ work when attempted manually, so I think we should treat this in a separate broken builds issue.

2023-02-07 00:35 UTC, emteknetnz approved these changes

2023-02-07 00:35 UTC, merged