FIX Validate Category / Tag Titles
silverstripe/silverstripe-blog pull request #700
Opened 2023-01-31 19:03 UTC by freezernick

Closes #695

2023-01-31 21:02 UTC, michalkleiner commented on src/Model/BlogObject.php
> +        if(empty($this->Title)) {
```suggestion
        if (empty($this->Title)) {
```

2023-04-11 01:31 UTC, GuySartorelli reviewed
@silverstripe/core-team 
What's our thoughts about this in regards to semver?
Specifically, changing the validation rules for whether an empty value is valid or not.

On one hand, it seems like there's no valid reason to have an empty category/tag - but on the other, someone could very well be going `BlogTag::create()->write()` in a unit test, if the _value_ of the tag doesn't matter for that test.

2023-04-11 01:34 UTC, GuySartorelli requested changes

2023-04-11 01:34 UTC, GuySartorelli commented on src/Model/BlogObject.php
> +            $validation->addError($this->getEmptyTitleError(), self::EMPTY_TITLE_EXCEPTION);
```suggestion
            $validation->addError($this->getEmptyTitleError(), self::EMPTY_TITLE_EXCEPTION ?? 'EMPTY_TITLE');
```
The constant won't be declared on any custom classes that use this trait, and requiring it to be added is technically a breaking change.

Note: Please test that this actually works - I've not tried the null coalescing operator in this context before. I think it'll work but it'll pay to check.

2023-04-11 03:51 UTC, emteknetnz commented on src/Model/BlogObject.php
> +            $validation->addError($this->getEmptyTitleError(), self::EMPTY_TITLE_EXCEPTION);
Yikes, shouldn't be calling self::<const> on a trait.  Not a great choice when this was made back in the day

I don't think null coalescing works here

```php
class C { function F(){ var_dump(self::Z ?? 'default'); } }; (new C)->F();
// PHP Warning:  Uncaught Error: Undefined constant C::Z in php shell cod
```

2023-04-11 03:55 UTC, emteknetnz commented
>> someone could very well be going BlogTag::create()->write() in a unit test

No one other than core team is going to write new unit tests, and the existing unit tests are green on this PR, so I see no reason to be concerned here.

2023-04-11 04:02 UTC, GuySartorelli commented
> No one other than core team is going to write new unit tests

People write unit tests for their own projects and modules all the time. It's not super likely those tests will rely on blog tags or categories but it's also not impossible.

2023-04-11 07:15 UTC, emteknetnz commented
Oh sorry I meant "No one other than core team is going to write new unit tests _for the blog module_" :-) 

What's the concern? That a project will create their own unit test that instantiates a their own subclass of a  `BlogCategory` or `BlogTag` with a blank Title?  That's seems extremely unlikely.  And even if they did and their test fails, they'll get a pretty clear `Title must not be empty` error which should be easy to trace back, so fixing it should require minimal effort.

While we're very strict with respecting semver API in minor releases, historically we've been somewhat lenient/pragmatic with behavioral changes, including changes to default configuration values.  This PR seems at the low end of changes within a minor.

2023-04-11 08:40 UTC, michalkleiner commented
> What's our thoughts about this in regards to semver? Specifically, changing the validation rules for whether an empty value is valid or not.
> 
> On one hand, it seems like there's no valid reason to have an empty category/tag - but on the other, someone could very well be going `BlogTag::create()->write()` in a unit test, if the _value_ of the tag doesn't matter for that test.

Not bothered by this particular change, I agree with Steve on this.

2023-04-11 21:05 UTC, GuySartorelli commented
Sweet, just wanted to get the general feeling about it, since I was on the fence about it.
There's problems with how the constant is being applied, but sounds like the general approach is okay.

2023-10-05 23:40 UTC, GuySartorelli commented
@freezernick Are you still interested in this pull request being merged? If so, please make changes to how the constant is applied as requested above.

2023-11-08 08:10 UTC, GuySartorelli commented
I'm closing this due to inactivity. If you want to work on it again I'll be happy to reopen it, or you can open a new pull request from scratch.

2023-11-08 08:10 UTC, closed without merging