ENH Add generic types
silverstripe/silverstripe-blog pull request #739
Opened 2024-01-11 00:04 UTC by GuySartorelli

Requires https://github.com/silverstripe/silverstripe-framework/pull/11108 and the associated PRs in silverstripe/cms and silverstripe/lumberjack for these generics to take effect.

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11066

2024-01-17 20:59 UTC, emteknetnz requested changes

2024-01-17 20:59 UTC, emteknetnz commented on src/Model/BlogController.php
> +     * @return PaginatedList<ArrayList, BlogPost>
Could you just double check this is correct - `$allPosts = $this->blogPosts ?: ArrayList::create();` -  `$this->blogPosts` has a docblock var of DataList and when it's assigned by methods like getCurrentProfilePosts() it's a DataList

2024-01-17 22:19 UTC, GuySartorelli commented on src/Model/BlogController.php
> +     * @return PaginatedList<ArrayList, BlogPost>
Ahh, I must have missed that, good call. I'll just use `SS_List` instead - this method will probably mostly be called in a template anyway so doesn't matter too much.

2024-01-18 20:57 UTC, emteknetnz approved these changes

2024-01-18 20:58 UTC, merged