Changed BlogProfileImage publish from onBeforeWrite to $owns
silverstripe/silverstripe-blog pull request #750
Opened 2024-03-19 10:16 UTC by purplespider

_Redo of #749_
## Description

Due to the order in `onBeforeWrite`, the `BlogProfileImage` added in `BlogMemberExtension` doesn't get automatically published unless you have also changed the member's name (unlikely).

This is because if `FirstName` or `Surname` are unchanged, then `onBeforeWrite` returns, before being able to publish the profile image.

This PR sets it to use `$owns` to take care of publishing the image instead. 

## Manual testing steps

1. Create a new user in Security.
2. Click **Create**
3. **Upload** a new "Blog profile image" for the user.
4. Click **Save**

**What I expect to happen:** The image gets published.
**What actually happens:** The image stays as "Draft".

## Issues

- #748

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

2024-03-19 10:21 UTC, michalkleiner approved these changes

2024-03-19 21:55 UTC, GuySartorelli requested changes
Great! Thanks for doing this. Just one tiny change.

2024-03-19 21:55 UTC, GuySartorelli commented on src/Model/BlogMemberExtension.php
> +    private static $owns = [
```suggestion
    private static array $owns = [
```
No need to use PHPDoc when we're declaring new properties - we can just directly use typehints.

For now the typehint doesn't actually enforce anything, but in the future the config might actually validate types against typehints, so we try to add them in whenever we're adding new config.

2024-03-20 09:34 UTC, purplespider commented on src/Model/BlogMemberExtension.php
> +    private static $owns = [
Ah, good to know. Thanks. I was just making sure it was consistent with how it was done in `BlogPost.php`. https://github.com/silverstripe/silverstripe-blog/blob/37d2ccff76d04d6fd8c1f73146350a5e074d2652/src/Model/BlogPost.php#L88

2024-03-20 09:44 UTC, michalkleiner commented on src/Model/BlogMemberExtension.php
> +    private static $owns = [
Thanks @purplespider! Yeah, there's sometimes a conflict between how it's done currently vs how it would be done ideally going forward.

I reckon in this case Guy could've just pushed the change, leave a comment explaining the same as above, and already have it merged ;-)

2024-03-20 09:46 UTC, michalkleiner approved these changes

2024-03-20 09:58 UTC, michalkleiner commented
I've updated the commit message to have the [type prefix](https://docs.silverstripe.org/en/5/contributing/code/#commit-messages) as well (it's a FIX) and for it to be a bit more descriptive.

2024-03-20 10:00 UTC, merged

2024-03-20 20:05 UTC, GuySartorelli commented on src/Model/BlogMemberExtension.php
> +    private static $owns = [
I could have done. There's no hard and fast rules about what to let through and what not to. On the one hand it doesn't ultimately affect anything *right now* but on the other it's a small change so easy enough to make before merging.
I erred on the side of asking for the change in this case 🤷‍♀️