ENH Auto-scaffold blog categories and tags formfields
silverstripe/silverstripe-blog pull request #769
Opened 2024-06-19 01:31 UTC by GuySartorelli

See post-implementation note in the linked issue about these - short version is that this mirrors the implementation used in `BlogPost`, but I can't update `BlogPost` to take advantage of it just yet. That'll be handled in a separate issue.

## Issue
- https://github.com/silverstripe/.github/issues/262

2024-06-19 01:58 UTC, GuySartorelli commented
JS CI failure is unrelated to these changes

2024-06-20 03:10 UTC, emteknetnz requested changes

2024-06-20 03:10 UTC, emteknetnz commented on src/Model/BlogCategory.php
> +        $field = TagField::create(
Is there any reason to use TagField over SearchableMultiDropdownField?  From memory their UI is quite similar, though TagField could create (update?) new records from within the field (add a string, press enter, create/update a record), while SearchableMultiDropdownField is for linking existing records which I think is what we're doing here

2024-06-20 03:12 UTC, GuySartorelli commented on src/Model/BlogCategory.php
> +        $field = TagField::create(
TagField is what it's already using so I'm just copying that logic across.
But yes, the main difference is the ability to create new tags/categories directly in the formfield itself, which makes it quicker to add them.

I'm not aiming to change the way people add or create tags or categories with this PR.

2024-06-26 06:02 UTC, emteknetnz approved these changes
Tested locally, looks good

2024-06-26 22:44 UTC, merged