FIX Update CMS fields now that they're being scaffolded
silverstripe/silverstripe-blog pull request #775
Opened 2024-08-08 01:45 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/silverstripe-cms/issues/2767

2024-08-11 23:46 UTC, GuySartorelli commented on templates/SilverStripe/Blog/Forms/TabSet_holder.ss
This was never used!

2024-08-11 23:47 UTC, GuySartorelli commented on src/Model/BlogPost.php
> -        $fields->fieldByName('Root')->setTemplate('TabSet_holder');
The template name was wrong so this hasn't been used since namespaces were introduced. Just remove altogether at this point.

2024-08-12 02:31 UTC, GuySartorelli commented
PHP linting failure unrelated.
Other CI failures should go green when other PRs are merged (see kitchen sink CI run)

2024-08-13 22:38 UTC, emteknetnz approved these changes

2024-08-15 01:50 UTC, emteknetnz requested changes
Linting failure

2024-08-15 02:01 UTC, emteknetnz approved these changes

2024-08-15 02:01 UTC, merged